import numpy as np
from NSphere import NSphere
np.set_printoptions(precision=10)

class PropossalLogLikeDet:
    def __init__(self, data, ndims, sigma=0.5):
        self.N = len(data)
        self.ndims = ndims
        self.sigma = sigma
        # data contains the likelihoods and points generated by a NSphere objects
        points = data[:, :ndims]
        datalikes = data[:, ndims]
        print(np.shape(points), np.shape(datalikes))
        sort_by_likes = np.argsort(data[:,ndims], axis=0)
        print(sort_by_likes)
        self.points = points[sort_by_likes]
        self.datalikes = datalikes[sort_by_likes]
        print(np.shape(self.points))
        cov_matrix = np.cov(self.points)
        print(np.shape(cov_matrix))
        scale_cov_matrix = cov_matrix / np.amax(cov_matrix, axis=0, keepdims=True)
        self.det = np.linalg.det(scale_cov_matrix)
        print("|cov|: {}".format(self.det))

        sphere = NSphere(ndims)
        self.unit_vol = sphere.vol(1)

    def propossal_fn(self, logLmax, xMax, i, d):
        # xMax = np.exp(logxMax)
        return logLmax - 0.5 * np.sign(xMax) * (1./(self.unit_vol*np.power(self.det, 1./d))) *\
               np.sign(xMax) * ((i * np.abs(xMax) / self.N) ** (2 / d))

    def loglike_freeDim(self, theta):
        loglmax, xMax, d = theta
        i = np.arange(1, self.N + 1)
        chisq = np.sum(((self.datalikes -
                         self.propossal_fn(loglmax, xMax, i, d)) /
                         self.sigma) ** 2)

        return 0.5 * chisq

    def loglike_noDim(self, theta):
        loglmax, xMax = theta
        i = np.arange(1, self.N + 1)
        chisq = np.sum(((self.datalikes -
                         self.propossal_fn(loglmax, xMax, i, self.ndims)) /
                        self.sigma) ** 2)

        return 0.5 * chisq


